# Generated by Django 5.2.7 on 2025-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_filter', '0002_remove_track_explicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
