# Generated by Django 5.2.7 on 2025-12-01 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_filter", "0005_album_user_artist_user_alter_artist_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("user", "spotify_id")},
        ),
    ]
