# Generated by Django 5.2.7 on 2025-12-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_filter", "0006_alter_album_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="spotify_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="artist",
            name="spotify_id",
            field=models.CharField(max_length=50),
        ),
    ]
