# Generated by Django 5.2.7 on 2025-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_filter", "0007_alter_album_spotify_id_alter_artist_spotify_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="access_token",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=500),
        ),
    ]
