# Generated by Django 5.2.7 on 2025-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_filter", "0008_alter_spotifytoken_access_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="album_cover",
            new_name="album_cover_large",
        ),
        migrations.AddField(
            model_name="album",
            name="album_cover_medium",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="album_cover_small",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
