# Generated by Django 5.2.7 on 2025-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_filter", "0009_rename_album_cover_album_album_cover_large_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="image",
            new_name="image_large",
        ),
        migrations.AddField(
            model_name="artist",
            name="image_medium",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="image_small",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
